// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	domain "authService/domain"
	errs "authService/errs"

	mock "github.com/stretchr/testify/mock"
)

// UserRepositoryDB is an autogenerated mock type for the UserRepositoryDB type
type UserRepositoryDB struct {
	mock.Mock
}

// FetchByEmail provides a mock function with given fields: _a0
func (_m *UserRepositoryDB) FetchByEmail(_a0 string) (*domain.User, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(string) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: _a0
func (_m *UserRepositoryDB) FetchByID(_a0 string) (*domain.User, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(string) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// FetchByUsername provides a mock function with given fields: _a0
func (_m *UserRepositoryDB) FetchByUsername(_a0 string) (*domain.User, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(string) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// RepoHealthCheck provides a mock function with given fields:
func (_m *UserRepositoryDB) RepoHealthCheck() *errs.AppError {
	ret := _m.Called()

	var r0 *errs.AppError
	if rf, ok := ret.Get(0).(func() *errs.AppError); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errs.AppError)
		}
	}

	return r0
}
