// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RewardPointServiceClient is the client API for RewardPointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RewardPointServiceClient interface {
	GetRewardPoints(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rewardPointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRewardPointServiceClient(cc grpc.ClientConnInterface) RewardPointServiceClient {
	return &rewardPointServiceClient{cc}
}

func (c *rewardPointServiceClient) GetRewardPoints(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.RewardPointService/getRewardPoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RewardPointServiceServer is the server API for RewardPointService service.
// All implementations must embed UnimplementedRewardPointServiceServer
// for forward compatibility
type RewardPointServiceServer interface {
	GetRewardPoints(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRewardPointServiceServer()
}

// UnimplementedRewardPointServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRewardPointServiceServer struct {
}

func (UnimplementedRewardPointServiceServer) GetRewardPoints(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRewardPoints not implemented")
}
func (UnimplementedRewardPointServiceServer) mustEmbedUnimplementedRewardPointServiceServer() {}

// UnsafeRewardPointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RewardPointServiceServer will
// result in compilation errors.
type UnsafeRewardPointServiceServer interface {
	mustEmbedUnimplementedRewardPointServiceServer()
}

func RegisterRewardPointServiceServer(s grpc.ServiceRegistrar, srv RewardPointServiceServer) {
	s.RegisterService(&RewardPointService_ServiceDesc, srv)
}

func _RewardPointService_GetRewardPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RewardPointServiceServer).GetRewardPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RewardPointService/getRewardPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RewardPointServiceServer).GetRewardPoints(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RewardPointService_ServiceDesc is the grpc.ServiceDesc for RewardPointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RewardPointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RewardPointService",
	HandlerType: (*RewardPointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getRewardPoints",
			Handler:    _RewardPointService_GetRewardPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
