
# Health Status

# curl -H "X-API-Key: bd811560" https://my.api.mockaroo.com/api/auth
GET https://my.api.mockaroo.com/api/auth
X-API-Key: bd811560

###

# User Login

# curl -H "X-API-Key: bd811560" -X POST https://my.api.mockaroo.com/api/auth/login
POST https://my.api.mockaroo.com/api/auth/login
X-API-Key: bd811560

{
"username":"ayan59dutta",
"password":"pass@123#"
}

###

# curl -H "X-API-Key: bd811560" -X POST https://my.api.mockaroo.com/api/auth/login
POST https://my.api.mockaroo.com/api/auth/login
X-API-Key: bd811560

{
"email":"ayan59dutta@gmail.com",
"password":"pass@123#"
}

###

# User Logout

# curl -H "X-API-Key: bd811560" -X POST https://my.api.mockaroo.com/api/auth/logout
POST https://my.api.mockaroo.com/api/auth/logout
X-API-Key: bd811560

###
