// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ashwin Gopalsamy",
            "email": "ashwinyaal@gmail.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "used to check whether shipping service is up and running or not",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health of shipping service",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/checkout/api/cartItems": {
            "get": {
                "description": "Returns Cart Items using GET Request.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart Service"
                ],
                "summary": "Gets Cart Items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/checkout/api/payments": {
            "get": {
                "description": "Returns Payment Mode using GET Request.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Mode Service"
                ],
                "summary": "Gets Payment Mode",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/checkout/api/shippingaddress": {
            "get": {
                "description": "Returns default Shipping Address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShippingAddress Service"
                ],
                "summary": "Gets Default Shipping Address",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/existing/": {
            "get": {
                "description": "Returns default Shipping Address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShippingAddress Service"
                ],
                "summary": "Gets Default Shipping Address",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/payment/api/payments": {
            "get": {
                "description": "Returns default Payment Mode",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Service"
                ],
                "summary": "Gets Default Payment Mode",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/shipping/api/existing": {
            "get": {
                "description": "Returns default Shipping Address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShippingAddress Service"
                ],
                "summary": "Gets Default Shipping Address",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9002",
	BasePath:         "/checkout/api",
	Schemes:          []string{},
	Title:            "Swiggy Qwik - Checkout module",
	Description:      "This microservice is for checkout service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
