// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Response struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MetaDescription      string   `protobuf:"bytes,4,opt,name=meta_description,json=metaDescription,proto3" json:"meta_description,omitempty"`
	MetaKeyword          string   `protobuf:"bytes,5,opt,name=meta_keyword,json=metaKeyword,proto3" json:"meta_keyword,omitempty"`
	MetaTitle            string   `protobuf:"bytes,6,opt,name=meta_title,json=metaTitle,proto3" json:"meta_title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Response) GetMetaDescription() string {
	if m != nil {
		return m.MetaDescription
	}
	return ""
}

func (m *Response) GetMetaKeyword() string {
	if m != nil {
		return m.MetaKeyword
	}
	return ""
}

func (m *Response) GetMetaTitle() string {
	if m != nil {
		return m.MetaTitle
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() {
	proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba)
}

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xd3, 0x0a, 0x28, 0xa3, 0x52, 0x33, 0x5e, 0x56, 0x12, 0x13, 0xe4, 0xa4, 0x97, 0x36,
	0xc1, 0x37, 0x50, 0x6f, 0xde, 0x1a, 0x4f, 0x5e, 0x4c, 0xe9, 0x8e, 0x38, 0x41, 0xba, 0x65, 0x77,
	0x94, 0xf4, 0xe1, 0x7c, 0x37, 0xd3, 0x29, 0x9a, 0x86, 0xd3, 0xec, 0xff, 0xcd, 0xb7, 0x9b, 0xec,
	0x0f, 0x97, 0xb5, 0x77, 0xe2, 0xb2, 0x40, 0xfe, 0x9b, 0x4b, 0x4a, 0x35, 0xe1, 0x50, 0xc7, 0xfc,
	0x0a, 0x8e, 0x73, 0xda, 0x7e, 0x51, 0x10, 0x9c, 0x40, 0xcc, 0xd6, 0x44, 0xb3, 0xe8, 0x76, 0x9c,
	0xc7, 0x6c, 0xe7, 0x3f, 0x11, 0x9c, 0xe4, 0x14, 0x6a, 0x57, 0x05, 0x3a, 0x5c, 0x22, 0xc2, 0xa0,
	0x2a, 0x36, 0x64, 0x62, 0x25, 0x7a, 0xc6, 0x19, 0x9c, 0x5a, 0x0a, 0xa5, 0xe7, 0x5a, 0xd8, 0x55,
	0xe6, 0x48, 0x57, 0x7d, 0x84, 0x77, 0x70, 0xb1, 0x21, 0x29, 0xde, 0xfa, 0xda, 0x40, 0xb5, 0xa4,
	0xe5, 0x4f, 0x3d, 0xf5, 0x06, 0xce, 0x54, 0x5d, 0x53, 0xb3, 0x73, 0xde, 0x9a, 0x61, 0xf7, 0x5a,
	0xcb, 0x9e, 0x3b, 0x84, 0xd7, 0x00, 0xaa, 0x08, 0xcb, 0x27, 0x99, 0x91, 0x0a, 0xe3, 0x96, 0xbc,
	0xb4, 0x60, 0xf1, 0x08, 0xe7, 0xef, 0x24, 0xe5, 0x47, 0x59, 0x08, 0xad, 0x9c, 0x6f, 0x70, 0x01,
	0xc9, 0x8a, 0xe4, 0x2f, 0x2e, 0x1b, 0xb6, 0x38, 0xe9, 0xda, 0x48, 0xf7, 0x1d, 0x4c, 0x93, 0xff,
	0xdc, 0xfd, 0xfb, 0x61, 0xfa, 0x6a, 0xb6, 0x3b, 0x5e, 0xa7, 0x5c, 0x65, 0xfb, 0x8b, 0x4c, 0x21,
	0x53, 0x69, 0x39, 0xd2, 0x71, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x92, 0x3f, 0xff, 0x87, 0x60,
	0x01, 0x00, 0x00,
}
