// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FetchcategoryClient is the client API for Fetchcategory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FetchcategoryClient interface {
	Getcategorybyid(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type fetchcategoryClient struct {
	cc grpc.ClientConnInterface
}

func NewFetchcategoryClient(cc grpc.ClientConnInterface) FetchcategoryClient {
	return &fetchcategoryClient{cc}
}

func (c *fetchcategoryClient) Getcategorybyid(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.fetchcategory/getcategorybyid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FetchcategoryServer is the server API for Fetchcategory service.
// All implementations must embed UnimplementedFetchcategoryServer
// for forward compatibility
type FetchcategoryServer interface {
	Getcategorybyid(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFetchcategoryServer()
}

// UnimplementedFetchcategoryServer must be embedded to have forward compatible implementations.
type UnimplementedFetchcategoryServer struct {
}

func (UnimplementedFetchcategoryServer) Getcategorybyid(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Getcategorybyid not implemented")
}
func (UnimplementedFetchcategoryServer) mustEmbedUnimplementedFetchcategoryServer() {}

// UnsafeFetchcategoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FetchcategoryServer will
// result in compilation errors.
type UnsafeFetchcategoryServer interface {
	mustEmbedUnimplementedFetchcategoryServer()
}

func RegisterFetchcategoryServer(s grpc.ServiceRegistrar, srv FetchcategoryServer) {
	s.RegisterService(&Fetchcategory_ServiceDesc, srv)
}

func _Fetchcategory_Getcategorybyid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchcategoryServer).Getcategorybyid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.fetchcategory/getcategorybyid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchcategoryServer).Getcategorybyid(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Fetchcategory_ServiceDesc is the grpc.ServiceDesc for Fetchcategory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fetchcategory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.fetchcategory",
	HandlerType: (*FetchcategoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getcategorybyid",
			Handler:    _Fetchcategory_Getcategorybyid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
