// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	protos "qwik.in/account-frontstore/protos"
)

// GrpcClientRepositoryInterface is an autogenerated mock type for the GrpcClientRepositoryInterface type
type GrpcClientRepositoryInterface struct {
	mock.Mock
}

// GetPaymentMethodsByCustomerId provides a mock function with given fields: customerId
func (_m *GrpcClientRepositoryInterface) GetPaymentMethodsByCustomerId(customerId string) []*protos.PaymentMode {
	ret := _m.Called(customerId)

	var r0 []*protos.PaymentMode
	if rf, ok := ret.Get(0).(func(string) []*protos.PaymentMode); ok {
		r0 = rf(customerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*protos.PaymentMode)
		}
	}

	return r0
}

// GetRewardPointsByCustomerId provides a mock function with given fields: customerId
func (_m *GrpcClientRepositoryInterface) GetRewardPointsByCustomerId(customerId string) int32 {
	ret := _m.Called(customerId)

	var r0 int32
	if rf, ok := ret.Get(0).(func(string) int32); ok {
		r0 = rf(customerId)
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}
