// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: protos/productPriceService.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity string `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *ProductPriceRequest) Reset() {
	*x = ProductPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_productPriceService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceRequest) ProtoMessage() {}

func (x *ProductPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_productPriceService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceRequest.ProtoReflect.Descriptor instead.
func (*ProductPriceRequest) Descriptor() ([]byte, []int) {
	return file_protos_productPriceService_proto_rawDescGZIP(), []int{0}
}

func (x *ProductPriceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductPriceRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type ProductsPriceRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*ProductPriceRequest `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *ProductsPriceRequests) Reset() {
	*x = ProductsPriceRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_productPriceService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductsPriceRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsPriceRequests) ProtoMessage() {}

func (x *ProductsPriceRequests) ProtoReflect() protoreflect.Message {
	mi := &file_protos_productPriceService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsPriceRequests.ProtoReflect.Descriptor instead.
func (*ProductsPriceRequests) Descriptor() ([]byte, []int) {
	return file_protos_productPriceService_proto_rawDescGZIP(), []int{1}
}

func (x *ProductsPriceRequests) GetProducts() []*ProductPriceRequest {
	if x != nil {
		return x.Products
	}
	return nil
}

type ResponsePrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *ResponsePrice) Reset() {
	*x = ResponsePrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_productPriceService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePrice) ProtoMessage() {}

func (x *ResponsePrice) ProtoReflect() protoreflect.Message {
	mi := &file_protos_productPriceService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePrice.ProtoReflect.Descriptor instead.
func (*ResponsePrice) Descriptor() ([]byte, []int) {
	return file_protos_productPriceService_proto_rawDescGZIP(), []int{2}
}

func (x *ResponsePrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_protos_productPriceService_proto protoreflect.FileDescriptor

var file_protos_productPriceService_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x41, 0x0a, 0x13, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x50, 0x0a,
	0x15, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22,
	0x25, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x67, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a,
	0x18, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x6f,
	0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x42,
	0x09, 0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_productPriceService_proto_rawDescOnce sync.Once
	file_protos_productPriceService_proto_rawDescData = file_protos_productPriceService_proto_rawDesc
)

func file_protos_productPriceService_proto_rawDescGZIP() []byte {
	file_protos_productPriceService_proto_rawDescOnce.Do(func() {
		file_protos_productPriceService_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_productPriceService_proto_rawDescData)
	})
	return file_protos_productPriceService_proto_rawDescData
}

var file_protos_productPriceService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_productPriceService_proto_goTypes = []interface{}{
	(*ProductPriceRequest)(nil),   // 0: protos.ProductPriceRequest
	(*ProductsPriceRequests)(nil), // 1: protos.ProductsPriceRequests
	(*ResponsePrice)(nil),         // 2: protos.ResponsePrice
}
var file_protos_productPriceService_proto_depIdxs = []int32{
	0, // 0: protos.ProductsPriceRequests.products:type_name -> protos.ProductPriceRequest
	1, // 1: protos.ProductPriceService.getTotalPriceForProducts:input_type -> protos.ProductsPriceRequests
	2, // 2: protos.ProductPriceService.getTotalPriceForProducts:output_type -> protos.ResponsePrice
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_productPriceService_proto_init() }
func file_protos_productPriceService_proto_init() {
	if File_protos_productPriceService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_productPriceService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_productPriceService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductsPriceRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_productPriceService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_productPriceService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_productPriceService_proto_goTypes,
		DependencyIndexes: file_protos_productPriceService_proto_depIdxs,
		MessageInfos:      file_protos_productPriceService_proto_msgTypes,
	}.Build()
	File_protos_productPriceService_proto = out.File
	file_protos_productPriceService_proto_rawDesc = nil
	file_protos_productPriceService_proto_goTypes = nil
	file_protos_productPriceService_proto_depIdxs = nil
}
